name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Trivial test
        run: |
          echo "Running trivial test"
          test 1 -eq 1
      - name: Force fail
        run: exit 1
